# ######################################################################### #
# Georgiev Lab (c) 2015-2016                                                #
# ######################################################################### #
# Department of Cybernetics                                                 #
# Faculty of Applied Sciences                                               #
# University of West Bohemia in Pilsen                                      #
# ######################################################################### #
#                                                                           #
# This file is part of CeCe.                                                #
#                                                                           #
# CeCe is free software: you can redistribute it and/or modify              #
# it under the terms of the GNU General Public License as published by      #
# the Free Software Foundation, either version 3 of the License, or         #
# (at your option) any later version.                                       #
#                                                                           #
# CeCe is distributed in the hope that it will be useful,                   #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with CeCe.  If not, see <http://www.gnu.org/licenses/>.             #
#                                                                           #
# ######################################################################### #

sudo: required
dist: trusty

cache: ccache

# Disable build for AppVeyor branch
branches:
    except:
        - appveyor

# Environment variables
env:
    global:
        - secure: "qgvwzJSqwKwdSCBVoK5Inttj+U5eYjnadKMTDB+luwRUm5uRwbMG1bDyLgXUeeEistUDfp5Nwnwfbawc9FG0p4Zeb9q7KplrFPkFLMEUPsMaSWTuM8+mjWgbyVi2aPPebQUEG23XtTMvcTDCl6/8Qzan1Yaw/pqPoqzGA2ssH5MSx8GaKnMKyf+4FEglPH7Dv5JI07bWIQETr879ymBNueur8/ITlO+La43Kp8TQ4XREltI97+S7Yuls2Du92Bf9VubRX4CpUEmeueH2Mgktfsc3PFwjUT/40lVMo/RpkDcBb9tHNNJ+46x2koQOhGTnN0ZPqlQCFoshyZK6ixN5a12cphX5gVXvA3BbvKPMw2ZdregmoVOSnYKZU6mODETxM14wlsvwpv20ginOq9GRUc3+CD15IhdUbAF3DoUtzVrEnRBCM2R19v8zbMvyb2dC630x/4oyx6iKo1EnWpyJV66Vf8xK0rCjxmiVS7+MX0y3JZ4HtG/qYm/nhBbNdgv7M7r60d+CfhLbCMXZZTuZE9hBbeMIBPkewPLr0QXd6/g8MsXnl0r8WfbWE+GrqZdgNIunikrnO3dvX8W2cuLDxyGGVotky9bLyCJ0wgxemVyd0e+/OueQY5WxGSAd5sQk6o6TqHdHUSo8xIObAWFVLfbT9dWrag050dOBs9Lx99U="
        - secure: "m6zSg9wOlKzGnIRbSU04AxddkhfvstrFymXbFGRFWs3rO4jwc3px0mFvo6/jc3vfeKXdYqxDsJzJUmHphoKIwHhjpzyp+JtlrPSjbJtlvAow4Nud8cgC7AdDMtCvcLRMsbJ8IJNP9e028NoLpApH/4XhKshA3InM6Idt059gglIJA1E+vmJtkPomM4Z1acyPdwWP7DhAujdllqiHtECiPVm4wykU5/Tn0vbKSxi9pfhkzwEs2CDLz22ZFKlhE6RAfLzYs6QAeudRvwFE2he77rQpkIFRsUSc4/96aV3rMYAj4U7RKf8v5VVSMsQeeEshyzyAq/r1Pp/gGAB88FIfZ1N3UZZTk666eO7CCw0j3IRYd17B7pJEpOR9yE6tm661lY9tkcp4m1AVczD+gviioOz6h93m5yaV4tXg9VhFxSoi7c83ypQ8SxjJFHRKCGxX1rInwytCXd2j19GWNelDbVOI0qidSBK1yfhGYw7QDh1T13GWy6lZ9rMEoAM3BDdxbljkIRP4VyO/qurWrl2thbdyXOSeJBMTQICF7mrTe7f6pf16nTIlyYgiM4GrlurheHdOE6umRJqy4HTpxq5H+HtJ80Gl3llllJE7w/7kD1j7lJ6jEQoW5NPpjA+AExPi8gseeuW3Ra1vCnRZkF1jGPipRPUn3aGtk08z0EJd1oU="
        - secure: "iQhGi2qz32pma5BbajCZ7CJy87SvTg03TzI1H7i0evl+7EO3BruYAxZpHDGYWvVliBy+XSo2uKxf83npiNICH8XlrZXCEHj/8/NQUSYAxrTGTq9L6/H3JwYs/C5ZkmAqlWdUv1KhCCAV6V9Q9GUbsVevL87FPzCFpgfHsiEj+ES531eKGbuTs/gk8DmRCI6LxWKekEFzKEKtluFfX6APHAIlQMT68uCRNy6ziSMB7dqDzx7gE/KST3L5Fkh12WIlR8QpPdY/7Z3eNalq71E8yDGAkeg4yaZ810X78C+58oie1wWow3ypiwwImRXyszwZVqp62j9G331imNzQkvq/YiRNVNZ5euKi3Hdstb6u5+Z9eahp0GJPTMvKPYV3xPDRNRkmavbDOko5SjJT6FGYTLYbYQie3/Qhb5898Sj4/l1ikLLANGDt4PE8gMuV1/Qxf8eIIZnXahGh4xRMVCTL+PO5gCNU2z++JBoHOU8HDdeyiZ6261Wd0ponlAphA9sfEIShq14HHnHiD2PBv4PjHdKv8T9qLwWo8/seXoEo2iTLcI7atwXt4wNCAEOWsVqzv2irdMQWyTxkwvKT61FUxArbq0YTTeMme+qFAhNAeP941ll4pPcYkgwxMaJJC8skHblgdj9nwWtkeTjls3lGme8y0N1LL4DpOuMbTnrd8y0="

matrix:
    include:
        - os: linux
          compiler: gcc
          env: CECE_RENDER=On DEPLOY=On
        - os: linux
          compiler: gcc
          env: CECE_RENDER=Off DEPLOY=Off
        - os: linux
          compiler: clang
          env: CECE_RENDER=On DEPLOY=Off
        - os: linux
          compiler: clang
          env: CECE_RENDER=Off DEPLOY=Off
        - os: osx
          compiler: clang
          env: CECE_RENDER=On DEPLOY=On
        - os: osx
          compiler: clang
          env: CECE_RENDER=Off DEPLOY=Off
        - os: osx
          compiler: gcc
          env: CECE_RENDER=On DEPLOY=Off
        - os: osx
          compiler: gcc
          env: CECE_RENDER=Off DEPLOY=Off

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - clang-3.6
            - libgl1-mesa-dev
            - xorg-dev
            - libgl1-mesa-dev

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated cmake  || brew upgrade cmake  ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated ccache || brew upgrade ccache ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated libpng || brew upgrade libpng ; fi

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
    - mkdir build
    - pushd build
    - cmake -DCMAKE_BUILD_TYPE=release -DCECE_TESTS_BUILD=On -DCECE_RENDER=$CECE_RENDER ..
    - popd

script:
    - VERBOSE=1 cmake --build build

after_success:
    - pushd build
    - GTEST_COLOR=1 ctest --verbose
    - popd

notifications:
    slack:
        secure: "Ea08dt4n5FNh881ZI+6A8auP9/QHjikCJMfQmJKcwL+/J+rIpmHRu/LkwfSy6BpeadX71JE3oQTokHz0fod71tAP6HDpaT+CStG2Bk0Z+499bl3EZkWM2AxaKTxn1W8U0kz8zv66YYai0b/YoBKPxyb7dA4dUv6oK9KrQL3Z6Xx+YiWM/XvDY9LBEb4lr0U0MMH4XAx+KJrGUEiGakLMwLh1pxs4rI1pG4namEkjqPAkornkvhfQIt15BP+tGoehvmiX6YCsDDSWUr1ZbWxicSXNb00CqkaopB0q0sx8Z63AjewljBUJrqbYe3kWMsAofAiDgjnpknhnFLYZQ4K9Vtl2aCi+S10IStFwCgqeM1QDiwGCrXpMfYzC6MkBEXCUQiquzYLNukdI0l/oGqnobSYZSzv5RY++EyaHhnM+MQEhYkf0nvAeXPjnzS8jHUswhJ3hLtznAfqBv3w1SvqhBWd5HebensdgDU8KOFR4h1PwSsq9fwzHzCZzjB0yDIbL2wzulbsx/7dz+x5RrrzgQbBc7z5Tjx7A0aA/A9r/7UoRRM7dZui10e9md45e12X8rrTuEBf4zXgpW9Ddt5qEFLxgqbgJI/XuGpKNgrmMSSy6C3r4TrXUWhG20Fu5g5d7lPMFC01ZQP2M8UJL6kzYlnhljjH38tgTeylwL2vsaWo="

deploy:
    provider: script
    script: scripts/ci/deploy.sh
    skip_cleanup: true
    on:
        branch: master
        condition: "$DEPLOY = On"

# ######################################################################### #
